include: package:lints/recommended.yaml

analyzer:
  exclude:
    # Exclude generated files which often use alternative styling
    - lib/src/generated/

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - collection_methods_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - require_trailing_commas
