name: coinlib_flutter
description: A flutter wrapper for coinlib
version: 1.0.0-alpha
repository: https://github.com/peercoin/coinlib

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.17.0"

dependencies:
  coinlib: ^1.0.0-alpha
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
